# -*- coding: utf-8 -*-

"""
   marvelcomicslib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "http://gateway.marvel.com"

    referer = "*.marvel.com";

    apikey = "";


