# -*- coding: utf-8 -*-

"""
    marvelcomicslib.marvel_comics_client

    This file was automatically generated by APIMATIC BETA v2.0 on 07/21/2016
"""

from marvelcomicslib.http import *
from marvelcomicslib.models import *
from marvelcomicslib.controllers import *
from marvelcomicslib.decorators import *
from marvelcomicslib.api_exception import *

class MarvelComicsClient(object):

    @lazy_property
    def characters(self):
        return CharactersController()

    @lazy_property
    def comics(self):
        return ComicsController()

    @lazy_property
    def events(self):
        return EventsController()

    @lazy_property
    def series(self):
        return SeriesController()

    @lazy_property
    def stories(self):
        return StoriesController()

    @lazy_property
    def creators(self):
        return CreatorsController()


    def __init__(self, 
                 referer = None,
                 apikey = None):

        Configuration.referer = referer
        Configuration.apikey = apikey


