# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.character_summary
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class CharacterSummary(BaseModel):

    """Implementation of the 'CharacterSummary' model.

    TODO: type model description here.

    Attributes:
        name (string): The full name of the character.
        resource_uri (string): The path to the individual character resource.
        role (string): The role of the creator in the parent entity.

    """

    def __init__(self, 
                 name = None,
                 resource_uri = None,
                 role = None):
        """Constructor for the CharacterSummary class"""
        
        # Initialize members of the class
        self.name = name
        self.resource_uri = resource_uri
        self.role = role

        # Create a mapping from Model property names to API property names
        self.names = {
            "name": "name",
            "resource_uri": "resourceURI",
            "role": "role",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            name = dictionary.get("name")
            resource_uri = dictionary.get("resourceURI")
            role = dictionary.get("role")
            # Return an object of this model
            return cls(name,
                       resource_uri,
                       role)
