# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.character
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

import dateutil.parser
from marvelcomicslib.models.base_model import BaseModel
from marvelcomicslib.models.comic_list import ComicList
from marvelcomicslib.models.event_list import EventList
from marvelcomicslib.models.series_list import SeriesList
from marvelcomicslib.models.story_list import StoryList
from marvelcomicslib.models.thumbnail import Thumbnail
from marvelcomicslib.models.url_model import UrlModel

class Character(BaseModel):

    """Implementation of the 'Character' model.

    TODO: type model description here.

    Attributes:
        comics (ComicList): A resource list containing comics which feature
            this character.
        description (string): A short bio or description of the character.
        events (EventList): A resource list of events in which this character
            appears.
        id (int): The unique ID of the character resource.
        modified (DateTime): The date the resource was most recently
            modified.
        name (string): The name of the character.
        resource_uri (string): The canonical URL identifier for this
            resource.
        series (SeriesList): A resource list of series in which this character
            appears.
        stories (StoryList): A resource list of stories in which this
            character appears.
        thumbnail (Thumbnail): The representative image for this character.
        urls (list of UrlModel): A set of public web site URLs for the
            resource.

    """

    def __init__(self, 
                 comics = None,
                 description = None,
                 events = None,
                 id = None,
                 modified = None,
                 name = None,
                 resource_uri = None,
                 series = None,
                 stories = None,
                 thumbnail = None,
                 urls = None):
        """Constructor for the Character class"""
        
        # Initialize members of the class
        self.comics = comics
        self.description = description
        self.events = events
        self.id = id
        self.modified = modified
        self.name = name
        self.resource_uri = resource_uri
        self.series = series
        self.stories = stories
        self.thumbnail = thumbnail
        self.urls = urls

        # Create a mapping from Model property names to API property names
        self.names = {
            "comics": "comics",
            "description": "description",
            "events": "events",
            "id": "id",
            "modified": "modified",
            "name": "name",
            "resource_uri": "resourceURI",
            "series": "series",
            "stories": "stories",
            "thumbnail": "thumbnail",
            "urls": "urls",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            comics = ComicList.from_dictionary(dictionary.get("comics")) if dictionary.get("comics") else None
            description = dictionary.get("description")
            events = EventList.from_dictionary(dictionary.get("events")) if dictionary.get("events") else None
            id = dictionary.get("id")
            modified = dateutil.parser.parse(dictionary.get("modified")) if dictionary.get("modified") else None
            name = dictionary.get("name")
            resource_uri = dictionary.get("resourceURI")
            series = SeriesList.from_dictionary(dictionary.get("series")) if dictionary.get("series") else None
            stories = StoryList.from_dictionary(dictionary.get("stories")) if dictionary.get("stories") else None
            thumbnail = Thumbnail.from_dictionary(dictionary.get("thumbnail")) if dictionary.get("thumbnail") else None
            urls = None
            if dictionary.get("urls") != None:
                urls = list()
                for structure in dictionary.get("urls"):
                    urls.append(UrlModel.from_dictionary(structure))
            # Return an object of this model
            return cls(comics,
                       description,
                       events,
                       id,
                       modified,
                       name,
                       resource_uri,
                       series,
                       stories,
                       thumbnail,
                       urls)
