# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.comic_price
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class ComicPrice(BaseModel):

    """Implementation of the 'ComicPrice' model.

    TODO: type model description here.

    Attributes:
        price (float): The price (all prices in USD).
        mtype (string): A description of the price (e.g. print price, digital
            price).

    """

    def __init__(self, 
                 price = None,
                 mtype = None):
        """Constructor for the ComicPrice class"""
        
        # Initialize members of the class
        self.price = price
        self.mtype = mtype

        # Create a mapping from Model property names to API property names
        self.names = {
            "price": "price",
            "mtype": "type",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            price = dictionary.get("price")
            mtype = dictionary.get("type")
            # Return an object of this model
            return cls(price,
                       mtype)
