# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.comic_date
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

import dateutil.parser
from marvelcomicslib.models.base_model import BaseModel


class ComicDate(BaseModel):

    """Implementation of the 'ComicDate' model.

    TODO: type model description here.

    Attributes:
        date (DateTime): The date.
        mtype (string): A description of the date (e.g. onsale date, FOC
            date).

    """

    def __init__(self, 
                 date = None,
                 mtype = None):
        """Constructor for the ComicDate class"""
        
        # Initialize members of the class
        self.date = date
        self.mtype = mtype

        # Create a mapping from Model property names to API property names
        self.names = {
            "date": "date",
            "mtype": "type",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            date = dateutil.parser.parse(dictionary.get("date")) if dictionary.get("date") else None
            mtype = dictionary.get("type")
            # Return an object of this model
            return cls(date,
                       mtype)
