# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.date_descriptor_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

class DateDescriptorEnum(object):

    """Implementation of the 'dateDescriptor' enum.

    TODO: type enum description here.

    Attributes:
        LASTWEEK: TODO: type description here.
        NEXTWEEK: TODO: type description here.
        THISMONTH: TODO: type description here.
        THISWEEK: TODO: type description here.

    """

    LASTWEEK = "lastWeek"

    NEXTWEEK = "nextWeek"

    THISMONTH = "thisMonth"

    THISWEEK = "thisWeek"

