# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.event
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

import dateutil.parser
from marvelcomicslib.models.base_model import BaseModel
from marvelcomicslib.models.character_list import CharacterList
from marvelcomicslib.models.comic_list import ComicList
from marvelcomicslib.models.creator_list import CreatorList
from marvelcomicslib.models.event_summary import EventSummary
from marvelcomicslib.models.series_list import SeriesList
from marvelcomicslib.models.story_list import StoryList
from marvelcomicslib.models.thumbnail import Thumbnail
from marvelcomicslib.models.url_model import UrlModel

class Event(BaseModel):

    """Implementation of the 'Event' model.

    TODO: type model description here.

    Attributes:
        characters (CharacterList): A resource list containing the characters
            which appear in this event.
        comics (ComicList): A resource list containing the comics in this
            event.
        creators (CreatorList): A resource list containing creators whose work
            appears in this event.
        description (string): A description of the event.
        end (DateTime): The date of publication of the last issue in this
            event.
        id (int): The unique ID of the event resource.
        modified (DateTime): The date the resource was most recently
            modified.
        next (EventSummary): A summary representation of the event which
            follows this event.
        previous (EventSummary): A summary representation of the event which
            preceded this event.
        resource_uri (string): The canonical URL identifier for this
            resource.
        series (SeriesList): A resource list containing the series in this
            event.
        start (DateTime): The date of publication of the first issue in this
            event.
        stories (StoryList): A resource list containing the stories in this
            event.
        thumbnail (Thumbnail): The representative image for this event.
        title (string): The title of the event.
        urls (list of UrlModel): A set of public web site URLs for the event.

    """

    def __init__(self, 
                 characters = None,
                 comics = None,
                 creators = None,
                 description = None,
                 end = None,
                 id = None,
                 modified = None,
                 next = None,
                 previous = None,
                 resource_uri = None,
                 series = None,
                 start = None,
                 stories = None,
                 thumbnail = None,
                 title = None,
                 urls = None):
        """Constructor for the Event class"""
        
        # Initialize members of the class
        self.characters = characters
        self.comics = comics
        self.creators = creators
        self.description = description
        self.end = end
        self.id = id
        self.modified = modified
        self.next = next
        self.previous = previous
        self.resource_uri = resource_uri
        self.series = series
        self.start = start
        self.stories = stories
        self.thumbnail = thumbnail
        self.title = title
        self.urls = urls

        # Create a mapping from Model property names to API property names
        self.names = {
            "characters": "characters",
            "comics": "comics",
            "creators": "creators",
            "description": "description",
            "end": "end",
            "id": "id",
            "modified": "modified",
            "next": "next",
            "previous": "previous",
            "resource_uri": "resourceURI",
            "series": "series",
            "start": "start",
            "stories": "stories",
            "thumbnail": "thumbnail",
            "title": "title",
            "urls": "urls",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            characters = CharacterList.from_dictionary(dictionary.get("characters")) if dictionary.get("characters") else None
            comics = ComicList.from_dictionary(dictionary.get("comics")) if dictionary.get("comics") else None
            creators = CreatorList.from_dictionary(dictionary.get("creators")) if dictionary.get("creators") else None
            description = dictionary.get("description")
            end = dateutil.parser.parse(dictionary.get("end")) if dictionary.get("end") else None
            id = dictionary.get("id")
            modified = dateutil.parser.parse(dictionary.get("modified")) if dictionary.get("modified") else None
            next = EventSummary.from_dictionary(dictionary.get("next")) if dictionary.get("next") else None
            previous = EventSummary.from_dictionary(dictionary.get("previous")) if dictionary.get("previous") else None
            resource_uri = dictionary.get("resourceURI")
            series = SeriesList.from_dictionary(dictionary.get("series")) if dictionary.get("series") else None
            start = dateutil.parser.parse(dictionary.get("start")) if dictionary.get("start") else None
            stories = StoryList.from_dictionary(dictionary.get("stories")) if dictionary.get("stories") else None
            thumbnail = Thumbnail.from_dictionary(dictionary.get("thumbnail")) if dictionary.get("thumbnail") else None
            title = dictionary.get("title")
            urls = None
            if dictionary.get("urls") != None:
                urls = list()
                for structure in dictionary.get("urls"):
                    urls.append(UrlModel.from_dictionary(structure))
            # Return an object of this model
            return cls(characters,
                       comics,
                       creators,
                       description,
                       end,
                       id,
                       modified,
                       next,
                       previous,
                       resource_uri,
                       series,
                       start,
                       stories,
                       thumbnail,
                       title,
                       urls)
