# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.format_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

class FormatTypeEnum(object):

    """Implementation of the 'formatType' enum.

    TODO: type enum description here.

    Attributes:
        COLLECTION: TODO: type description here.
        COMIC: TODO: type description here.

    """

    COLLECTION = "collection"

    COMIC = "comic"

