# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.series
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

import dateutil.parser
from marvelcomicslib.models.base_model import BaseModel
from marvelcomicslib.models.character_list import CharacterList
from marvelcomicslib.models.comic_list import ComicList
from marvelcomicslib.models.creator_list import CreatorList
from marvelcomicslib.models.event_list import EventList
from marvelcomicslib.models.series_summary import SeriesSummary
from marvelcomicslib.models.story_list import StoryList
from marvelcomicslib.models.thumbnail import Thumbnail
from marvelcomicslib.models.url_model import UrlModel

class Series(BaseModel):

    """Implementation of the 'Series' model.

    TODO: type model description here.

    Attributes:
        characters (CharacterList): A resource list containing characters
            which appear in comics in this series.
        comics (ComicList): A resource list containing comics in this series.
        creators (CreatorList): A resource list of creators whose work appears
            in comics in this series.
        description (string): A description of the series.
        end_year (int): The last year of publication for the series
            (conventionally, 2099 for ongoing series) .
        events (EventList): A resource list containing events which take place
            in comics in this series.
        id (int): The unique ID of the series resource.
        modified (DateTime): The date the resource was most recently
            modified.
        next (SeriesSummary): A summary representation of the series which
            follows this series.
        previous (SeriesSummary): A summary representation of the series which
            preceded this series.
        rating (string): The age-appropriateness rating for the series.
        resource_uri (string): The canonical URL identifier for this
            resource.
        start_year (int): The first year of publication for the series.
        stories (StoryList): A resource list containing stories which occur in
            comics in this series.
        thumbnail (Thumbnail): The representative image for this series.
        title (string): The canonical title of the series.
        urls (list of UrlModel): A set of public web site URLs for the
            resource.

    """

    def __init__(self, 
                 characters = None,
                 comics = None,
                 creators = None,
                 description = None,
                 end_year = None,
                 events = None,
                 id = None,
                 modified = None,
                 next = None,
                 previous = None,
                 rating = None,
                 resource_uri = None,
                 start_year = None,
                 stories = None,
                 thumbnail = None,
                 title = None,
                 urls = None):
        """Constructor for the Series class"""
        
        # Initialize members of the class
        self.characters = characters
        self.comics = comics
        self.creators = creators
        self.description = description
        self.end_year = end_year
        self.events = events
        self.id = id
        self.modified = modified
        self.next = next
        self.previous = previous
        self.rating = rating
        self.resource_uri = resource_uri
        self.start_year = start_year
        self.stories = stories
        self.thumbnail = thumbnail
        self.title = title
        self.urls = urls

        # Create a mapping from Model property names to API property names
        self.names = {
            "characters": "characters",
            "comics": "comics",
            "creators": "creators",
            "description": "description",
            "end_year": "endYear",
            "events": "events",
            "id": "id",
            "modified": "modified",
            "next": "next",
            "previous": "previous",
            "rating": "rating",
            "resource_uri": "resourceURI",
            "start_year": "startYear",
            "stories": "stories",
            "thumbnail": "thumbnail",
            "title": "title",
            "urls": "urls",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            characters = CharacterList.from_dictionary(dictionary.get("characters")) if dictionary.get("characters") else None
            comics = ComicList.from_dictionary(dictionary.get("comics")) if dictionary.get("comics") else None
            creators = CreatorList.from_dictionary(dictionary.get("creators")) if dictionary.get("creators") else None
            description = dictionary.get("description")
            end_year = dictionary.get("endYear")
            events = EventList.from_dictionary(dictionary.get("events")) if dictionary.get("events") else None
            id = dictionary.get("id")
            modified = dateutil.parser.parse(dictionary.get("modified")) if dictionary.get("modified") else None
            next = SeriesSummary.from_dictionary(dictionary.get("next")) if dictionary.get("next") else None
            previous = SeriesSummary.from_dictionary(dictionary.get("previous")) if dictionary.get("previous") else None
            rating = dictionary.get("rating")
            resource_uri = dictionary.get("resourceURI")
            start_year = dictionary.get("startYear")
            stories = StoryList.from_dictionary(dictionary.get("stories")) if dictionary.get("stories") else None
            thumbnail = Thumbnail.from_dictionary(dictionary.get("thumbnail")) if dictionary.get("thumbnail") else None
            title = dictionary.get("title")
            urls = None
            if dictionary.get("urls") != None:
                urls = list()
                for structure in dictionary.get("urls"):
                    urls.append(UrlModel.from_dictionary(structure))
            # Return an object of this model
            return cls(characters,
                       comics,
                       creators,
                       description,
                       end_year,
                       events,
                       id,
                       modified,
                       next,
                       previous,
                       rating,
                       resource_uri,
                       start_year,
                       stories,
                       thumbnail,
                       title,
                       urls)
