# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.story_summary
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class StorySummary(BaseModel):

    """Implementation of the 'StorySummary' model.

    TODO: type model description here.

    Attributes:
        name (string): The canonical name of the story.
        resource_uri (string): The path to the individual story resource.
        mtype (string): The type of the story (interior or cover).

    """

    def __init__(self, 
                 name = None,
                 resource_uri = None,
                 mtype = None):
        """Constructor for the StorySummary class"""
        
        # Initialize members of the class
        self.name = name
        self.resource_uri = resource_uri
        self.mtype = mtype

        # Create a mapping from Model property names to API property names
        self.names = {
            "name": "name",
            "resource_uri": "resourceURI",
            "mtype": "type",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            name = dictionary.get("name")
            resource_uri = dictionary.get("resourceURI")
            mtype = dictionary.get("type")
            # Return an object of this model
            return cls(name,
                       resource_uri,
                       mtype)
