# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.text_object
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class TextObject(BaseModel):

    """Implementation of the 'TextObject' model.

    TODO: type model description here.

    Attributes:
        language (string): The IETF language tag denoting the language the
            text object is written in.
        text (string): The text.
        mtype (string): The canonical type of the text object (e.g. solicit
            text, preview text, etc.).

    """

    def __init__(self, 
                 language = None,
                 text = None,
                 mtype = None):
        """Constructor for the TextObject class"""
        
        # Initialize members of the class
        self.language = language
        self.text = text
        self.mtype = mtype

        # Create a mapping from Model property names to API property names
        self.names = {
            "language": "language",
            "text": "text",
            "mtype": "type",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            language = dictionary.get("language")
            text = dictionary.get("text")
            mtype = dictionary.get("type")
            # Return an object of this model
            return cls(language,
                       text,
                       mtype)
