# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.thumbnail
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class Thumbnail(BaseModel):

    """Implementation of the 'Thumbnail' model.

    TODO: type model description here.

    Attributes:
        extension (string): TODO: type description here.
        path (string): TODO: type description here.

    """

    def __init__(self, 
                 extension = None,
                 path = None):
        """Constructor for the Thumbnail class"""
        
        # Initialize members of the class
        self.extension = extension
        self.path = path

        # Create a mapping from Model property names to API property names
        self.names = {
            "extension": "extension",
            "path": "path",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            extension = dictionary.get("extension")
            path = dictionary.get("path")
            # Return an object of this model
            return cls(extension,
                       path)
