# -*- coding: utf-8 -*-

"""
    marvelcomicslib.models.url_model
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/21/2016
"""

from marvelcomicslib.models.base_model import BaseModel


class UrlModel(BaseModel):

    """Implementation of the 'Url' model.

    TODO: type model description here.

    Attributes:
        mtype (string): A text identifier for the URL.
        url (string): A full URL (including scheme, domain, and path).

    """

    def __init__(self, 
                 mtype = None,
                 url = None):
        """Constructor for the UrlModel class"""
        
        # Initialize members of the class
        self.mtype = mtype
        self.url = url

        # Create a mapping from Model property names to API property names
        self.names = {
            "mtype": "type",
            "url": "url",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            mtype = dictionary.get("type")
            url = dictionary.get("url")
            # Return an object of this model
            return cls(mtype,
                       url)
